#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
export PATH

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/kirill/.lmstudio/bin"
# End of LM Studio CLI section

